import { Ubuntu } from "next/font/google";

// import "../globals.css";
import type { Metadata } from "next";

const ubuntu = Ubuntu({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashBoardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ubuntu.className}> dashboard {children}</body>
    </html>
  );
}
