import { Country } from "../_types/country";

export const COUNTRIES: Country[] = [
    {
        id: "aus",
        image: "/aus.jpg",
        country: "Australia",
        class: "",
        description: "",
        isCourseDetailAvailable: true,
    },
    {
        id: "uk",
        image: "/uk-2.jpg",
        country: "United Kingdom",
        class: "",
        description: "",
        isCourseDetailAvailable: false,
    },
    {
        id: "can",
        image: "/toronto.jpg",
        country: "Canada",
        class: "",
        description: "",
        isCourseDetailAvailable: false,
    },
    {
        id: "fin",
        image: "/finland-2.jpg",
        country: "Finland",
        class: "",
        description: "",
        isCourseDetailAvailable: false,
    },
    {
        id: "bal",
        image: "/belarus.jpg",
        country: "Belarus",
        class: "",
        description: "",
        isCourseDetailAvailable: false,
    },
    {
        id: "ger",
        image: "/germany.jpg",
        country: "Germany",
        class: "",
        description: "",
        isCourseDetailAvailable: false,
    },
    {
        id: "ita",
        image: "/italy.jpg",
        country: "Italy",
        class: "",
        description: "",
        isCourseDetailAvailable: false,
    },
    {
        id: "swe",
        image: "/sweden.jpg",
        country: "Sweden",
        class: "",
        description: "",
        isCourseDetailAvailable: false,
    },
    {
        id: "rus",
        image: "/russia.jpg",
        country: "Russia",
        class: "",
        description: "",
        isCourseDetailAvailable: false,
    },
    {
        id: "fra",
        image: "/france.jpg",
        country: "France",
        class: "",
        description: "",
        isCourseDetailAvailable: false,
    },
    {
        id: "ned",
        image: "/netherlands.jpg",
        country: "Netherlands",
        class: "",
        description: "",
        isCourseDetailAvailable: false,
    },
    {
        id: "lat",
        image: "/latvia.jpg",
        country: "Latvia",
        class: "",
        description: "",
        isCourseDetailAvailable: false,
    },
    {
        id: "swi",
        image: "/switzerland.jpg",
        country: "Switzerland",
        class: "",
        description: "",
        isCourseDetailAvailable: false,
    },
];

export const PRE_SELECTED_COUNTRY: Country = COUNTRIES[0]