import { MenuItem, MenuItemStatus, MenuItemType } from "../_types/menu.types";

export const MOCK_MENU_ITEMS: MenuItem[] = [
  {
    id: "1",
    label: "Home",
    href: "/",
    type: "link",
    status: "active",
    isVisible: true,
    order: 1,
    openInNewTab: false,
    children: [],
    createdAt: "2025-01-10T08:00:00Z",
    updatedAt: "2025-01-10T08:00:00Z",
  },
  {
    id: "2",
    label: "About Us",
    href: "/about",
    type: "link",
    status: "active",
    isVisible: true,
    order: 2,
    openInNewTab: false,
    children: [],
    createdAt: "2025-01-10T08:00:00Z",
    updatedAt: "2025-01-10T08:00:00Z",
  },
  {
    id: "3",
    label: "Destinations",
    href: "/destinations",
    type: "dropdown",
    status: "active",
    isVisible: true,
    order: 3,
    openInNewTab: false,
    children: [
      {
        id: "3-1",
        label: "United Kingdom",
        href: "/destinations/uk",
        isVisible: true,
        order: 1,
      },
      {
        id: "3-2",
        label: "Australia",
        href: "/destinations/australia",
        isVisible: true,
        order: 2,
      },
      {
        id: "3-3",
        label: "Canada",
        href: "/destinations/canada",
        isVisible: true,
        order: 3,
      },
      {
        id: "3-4",
        label: "Germany",
        href: "/destinations/germany",
        isVisible: false,
        order: 4,
      },
    ],
    createdAt: "2025-01-10T08:00:00Z",
    updatedAt: "2025-06-15T12:30:00Z",
  },
  {
    id: "4",
    label: "Services",
    href: "/services",
    type: "dropdown",
    status: "active",
    isVisible: true,
    order: 4,
    openInNewTab: false,
    children: [
      {
        id: "4-1",
        label: "Visa Assistance",
        href: "/services/visa",
        isVisible: true,
        order: 1,
      },
      {
        id: "4-2",
        label: "University Application",
        href: "/services/application",
        isVisible: true,
        order: 2,
      },
      {
        id: "4-3",
        label: "Scholarship Guidance",
        href: "/services/scholarship",
        isVisible: true,
        order: 3,
      },
    ],
    createdAt: "2025-01-10T08:00:00Z",
    updatedAt: "2025-01-10T08:00:00Z",
  },
  {
    id: "5",
    label: "Blog",
    href: "/blog",
    type: "link",
    status: "draft",
    isVisible: false,
    order: 5,
    openInNewTab: false,
    children: [],
    createdAt: "2025-03-20T09:00:00Z",
    updatedAt: "2025-03-20T09:00:00Z",
  },
  {
    id: "6",
    label: "Contact",
    href: "/contact",
    type: "link",
    status: "active",
    isVisible: true,
    order: 6,
    openInNewTab: false,
    children: [],
    createdAt: "2025-01-10T08:00:00Z",
    updatedAt: "2025-01-10T08:00:00Z",
  },
  {
    id: "7",
    label: "IELTS Resources",
    href: "/ielts",
    type: "link",
    status: "hidden",
    isVisible: false,
    order: 7,
    openInNewTab: true,
    children: [],
    createdAt: "2025-04-05T11:00:00Z",
    updatedAt: "2025-04-05T11:00:00Z",
  },
];

export const STATUS_CONFIG: Record<
  MenuItemStatus,
  { label: string; color: string; bg: string }
> = {
  active: {
    label: "Active",
    color: "text-emerald-700",
    bg: "bg-emerald-50 border-emerald-200",
  },
  draft: {
    label: "Draft",
    color: "text-amber-700",
    bg: "bg-amber-50 border-amber-200",
  },
  hidden: {
    label: "Hidden",
    color: "text-slate-600",
    bg: "bg-slate-100 border-slate-200",
  },
};

export const TYPE_CONFIG: Record<
  MenuItemType,
  { label: string; icon: string }
> = {
  link: { label: "Link", icon: "link" },
  dropdown: { label: "Dropdown", icon: "chevrons-down" },
  "mega-menu": { label: "Mega Menu", icon: "layout-grid" },
};
